jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: mayannaoliveira
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Profile Readme
        uses: actions-js/profile-readme@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
